/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.smallworld;

public class App {

    public static void main(String[] args) {

        TransactionDataFetcher tdf = new TransactionDataFetcher();
        System.out.println("\nMaximum Transaction Amount : " + tdf.getMaxTransactionAmount());

        System.out.println("\nTotal Unique Client : " + tdf.countUniqueClients());

        System.out.println("\nTotal Amount sent by \"Tom Shelby\" : " + tdf.getTotalTransactionAmountSentBy("Tom Shelby"));

        System.out.println("\nTotal Amount sent : " + tdf.getTotalTransactionAmount());

        System.out.println("\nTotal Transaction by Beneficary Arthur Shelby : "
                + tdf.getTransactionsByBeneficiaryName("Arthur Shelby"));

        System.out.println("\nList of Unresolved Issue Ids : " + tdf.getUnsolvedIssueIds());

        System.out.println("\nList of resolved Issue Messages : " + tdf.getAllSolvedIssueMessages());

        System.out.println(
                "\nHas Atleast one compliance issue of Michael Gray : " + tdf.hasOpenComplianceIssues("Michael Gray"));

        System.out.println("\nTop 3 transaction by amount : " + tdf.getTop3TransactionsByAmount());

        System.out.println("\nTop Sender by transaction amount : " + tdf.getTopSender());
    }

    @Override
    public String toString() {
        return "App []";
    }
}
